imports:
  - { resource: ../../src/Account/config/packages/doctrine.yaml }
  - { resource: ../../src/Other/config/packages/doctrine.yaml }

# See: https://symfony.com/doc/current/doctrine/multiple_entity_managers.html
doctrine:
  dbal:
    connections:
      # Default connection only for make:entity (See: https://github.com/symfony/maker-bundle/pull/1119)
      default:
        url: ''
        driver: 'pdo_pgsql'
        server_version: '14'
        charset: utf8

  orm:
    auto_generate_proxy_classes: true
    entity_managers:
      # Default entity_manager, only for make:entity (See: https://github.com/symfony/maker-bundle/pull/1119)
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          App:
            type: attribute
            dir: '%kernel.project_dir%/src/'
            prefix: 'App\Entity'
            alias: App

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
