# See: https://symfony.com/doc/current/doctrine/multiple_entity_managers.html
doctrine:
  dbal:
    connections:
      account:
        url: '%env(resolve:ACCOUNT_DATABASE_URL)%'
        driver: 'pdo_pgsql'
        server_version: '14'
        charset: utf8

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    entity_managers:
      account:
        connection: account
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          Account:
            type: attribute
            dir: '%kernel.project_dir%/src/Account/src/Infrastructure/Entity'
            prefix: 'Account\Infrastructure\Entity'
            alias: Account

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
