migrations_paths:
  # namespace is arbitrary but should be different from App\Migrations
  # as migrations classes should NOT be autoloaded
  'DoctrineMigrations': 'src/Account/migration/'
connection: account
em: account
